# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0071_auto_20160314_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='rejection_rate',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
