# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0074_auto_20160317_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerconfig',
            old_name='data',
            new_name='config',
        ),
        migrations.AddField(
            model_name='workerconfig',
            name='condition',
            field=models.SmallIntegerField(choices=[(1, b'BoomerangTreatment:TimerControl'), (2, b'BoomerangTreatment:TimerTreatment'), (3, b'BoomerangControl:TimerControl'), (4, b'BoomerangControl:TimerTreatment')], null=True),
        ),
    ]
