# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 21:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0075_auto_20160317_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequesterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.SmallIntegerField(choices=[(1, b'BoomerangTreatment:RejectionControl'), (2, b'BoomerangTreatment:RejectionTreatment'), (3, b'BoomerangControl:RejectionControl'), (4, b'BoomerangControl:RejectionTreatment')], null=True)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('requester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='crowdsourcing.Requester')),
            ],
        ),
    ]
