# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0072_merge'),
        ('crowdsourcing', '0077_auto_20160317_2219'),
    ]

    operations = [
    ]
