# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0078_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='has_read_tooltip',
            field=models.BooleanField(default=False),
        ),
    ]
