# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0079_userpreferences_has_read_tooltip'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
            ],
        ),
    ]
