# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0080_urlauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlauth',
            name='password',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlauth',
            name='username',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlauth',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
