# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0082_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequesterFeedRankings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='crowdsourcing.Requester')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_rankings', to='crowdsourcing.Worker')),
            ],
        ),
        migrations.AlterField(
            model_name='conversationrecipient',
            name='status',
            field=models.SmallIntegerField(choices=[(1, b'Open'), (2, b'Minimized'), (3, b'Closed'), (4, b'Muted')], default=1),
        ),
    ]
