# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 23:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0083_auto_20160325_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='has_read_tooltip_feed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
