# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0084_auto_20160327_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworker',
            name='system_completion_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='workerconfig',
            name='phase',
            field=models.SmallIntegerField(default=1),
        ),
    ]
