# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 10:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0086_workerconfig_phase_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField(max_length=4096)),
                ('task_id', models.IntegerField()),
                ('assignments', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
