# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0087_reviewabledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_id', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewableAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField()),
                ('answer', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ReviewableData',
            new_name='ReviewableTask',
        ),
        migrations.AddField(
            model_name='reviewableassignment',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_assignments', to='crowdsourcing.ReviewableTask'),
        ),
        migrations.AddField(
            model_name='assignmentreviews',
            name='assignment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='crowdsourcing.ReviewableAssignment'),
        ),
    ]
