# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 10:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0088_auto_20160402_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewabletask',
            name='assignments',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
