# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0089_auto_20160402_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewabletask',
            name='assignments',
        ),
        migrations.AlterField(
            model_name='reviewableassignment',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='crowdsourcing.ReviewableTask'),
        ),
    ]
