# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0090_auto_20160402_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewableassignment',
            name='worker_id',
            field=models.CharField(max_length=32),
        ),
    ]
