# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0091_auto_20160402_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentreviews',
            old_name='assignment_id',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='assignmentreviews',
            old_name='requester_id',
            new_name='requester',
        ),
    ]
