# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0092_auto_20160402_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewableassignment',
            name='accept',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reviewabletask',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
    ]
