# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0093_auto_20160405_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewableassignment',
            old_name='accept',
            new_name='status',
        ),
    ]
