# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0094_auto_20160405_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentreviews',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_reviews', to='crowdsourcing.Requester'),
        ),
    ]
