# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 17:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0095_auto_20160405_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Requester')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_choices', to='crowdsourcing.Worker')),
            ],
        ),
    ]
