# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0096_feedchoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequesterStudyResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=16384)),
                ('original_worker_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequesterStudyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('data', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='requesterconfig',
            name='phase',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requesterstudyresults',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_results', to='crowdsourcing.RequesterStudyTask'),
        ),
        migrations.AddField(
            model_name='requesterstudyresults',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_results', to='crowdsourcing.Worker'),
        ),
    ]
