# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 06:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0097_auto_20160411_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedChoicesRequester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_choices', to='crowdsourcing.Requester')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='requesterconfig',
            name='seen_workers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
