# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 11:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0099_auto_20160411_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesterconfig',
            name='seen_workers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
