# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0100_auto_20160411_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequesterStudyRels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField(default=1)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='crowdsourcing.Requester')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='crowdsourcing.RequesterStudyResults')),
            ],
        ),
    ]
